### ISSUE TITLE
wrong min size: should be Math.min(this.batchSize, records.size) as stated in the log line before

### ISSUE THREAD

**Issue by tpeikert** [jcustenborder/connect-utils#185]
https://github.com/jcustenborder/connect-utils/blob/701de970344599e492049a46474dba2124cd8e6d/connect-utils/src/main/java/com/github/jcustenborder/kafka/connect/utils/data/SourceRecordConcurrentLinkedDeque.java#L81

**Comment by jcustenborder** [comment]
@tpeikert Thanks for the issue. Are you running into this with one of my connectors? From a high level I don't think that class is really used that much anymore.

**Comment by tpeikert** [comment]
Sorry, I see now, that I misunderstood. I think the debug log and the names confused here. :) 
The debug log states that the batch size for this run will be calculated and then it states the max batch size and the resords.size, but I see now that List<SourceRecord> records is the list that gets filled and not drained. Therefor this.size is correct to calculate the batch size.
Again, sorry. I was wrong.
And no, I am reading your code because someone used it for a connector and I'm currently writing something very similar to their connector. Just different enough to have to write it yourself. :)

**Comment by jcustenborder** [comment]
All good. Take a look at this one though. This is the replacement for that class. I need to mark SourceRecordConcurrentLinkedDeque as deprecated. It has a lot more options and has been under heavy use for a while.

https://github.com/jcustenborder/connect-utils/blob/701de970344599e492049a46474dba2124cd8e6d/connect-utils/src/main/java/com/github/jcustenborder/kafka/connect/utils/data/SourceRecordDequeBuilder.java

**Comment by tpeikert** [comment]
Neat! Thanks.
